### ISSUE TITLE
Another question

### ISSUE THREAD

**Issue by a1029602653** [jwr1995/DTCN#2]
In seperation/train.py,line 261.I can't find a reference or function named `si_snr_with_permutation`.Looking forward to your answer。(●'◡'●)

**Comment by jwr1995** [comment]
@a1029602653 This shouldn't affect the ability to run the script as ```permutation_assign``` is never called. Thank you for pointing this out however. I will push another version later today with the functionality removed once I have had a a chance to test it

**Comment by jwr1995** [comment]
pushed this change and closing this issue
